/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "cgame-audiocallback-20230821-139-g66e7e86f"
#endif /* AVUTIL_FFVERSION_H */
