/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "Tag-2.3.5-2022-11-09-63-g26857dc8"
#endif /* AVUTIL_FFVERSION_H */
